export const facultyCoordinator = {
  name: "Dr. Manjula D Ghatak",
  role: "Faculty Coordinator",
  designation:"HoD,Mechanical Engineering",
  image: "/team/facultycoordinator.jpg",
}

export const president = {
  name: "Mr. Pintu Kumar Shah",
  role: "President",
  image: "/team/president.jpeg",
}

export const coreTeam = [
  {
    name: "Tapan Boruah",
    role: "Vice President",
    image: "/team/tapan.jpeg",
  },
  {
    name: "Anshu Priya",
    role: "Finance Secretary",
    image: "/team/anshu.jpeg",
  },
  {
    name: "Akash Raj",
    role: "Technical Lead",
    image: "/team/akash.jpeg",
  },
  {
    name: "Atul Kumar",
    role: "Event Coordinator",
    image: "/team/atul.jpg",
  },
  {
    name: "Ayush Kumar",
    role: "Programming Coordinator",
    image: "/team/ayush_k.jpg",
  },
  {
    name: "Kombongappun Ering",
    role: "Editor-in-Chief",
    image: "/team/kombong.jpeg",
  },
  {
    name: "Nitesh Kumar",
    role: "Hardware Lead",
    image: "/team/nitesh.jpeg",
  },
  {
    name: "Krish Prasad",
    role: "Web Coordinator",
    image: "/team/krish.jpeg",
  },

  {
    name: "Siddhant Hendry",
    role: "Overall Student Representative",
    image: "/team/siddhant.jpeg",
  },
  {
    name: "Rachana Lamba",
    role: "First Year Representative",
    image: "/team/rachana.PNG",
  },
  {
    name: "Vishal Raghuwanshi",
    role: "First Year Representative",
    image: "/team/vishal.jpeg",
  },
  {
    name: "Vaibhav Gupta",
    role: "Second Year Representative",
    image: "/team/vaibhav.jpeg",
  },
]

export const members = [
  { name: "Ankit Shukla" ,
    image:"/members/ankit_2.jpeg",
  },
  {name: "Roshni Yadav",
    image:"/members/roshni.jpeg",
},
  { name: "Anupam Gupta",
    image:"/members/anupam.jpeg" ,
},
  { name: "Subhajit Das",
    image:"/members/subhajit.jpeg" ,
},
  { name: "Dinkar Kumar Yadav",
    image:"/members/dinkar.jpeg" ,
},
  { name: "Jaisuria Barman",
    image:"/members/jaisuria.jpeg" ,
},
  { name: "Abhyuday Sharma" ,
    image:"/members/abhyuday.jpeg",
},
  { name: "Aditya Singh" ,
    image:"/members/aditya.jpeg",
},
  { name: "Ravi Kumar Srivastav",
    image:"/members/ravi_k.jpeg" ,
},
  { name: "Aryan Kumar" ,
    image:"/members/aryan.jpeg",
},
  { name: "Garvit Dumir" ,
    image:"/members/garvit.jpeg",
},
  { name: "Kunal Thakur" ,
    image:"/members/kunal.jpeg",
},
  { name: "Akhand Upadhyay",
    image:"/members/akhand.jpeg" ,
},
  { name: "Ayush Yadav" ,
    image:"/members/ayush_y.jpeg",
},
  { name: "Ankit Choudhary",
    image:"/members/ankit.jpeg" ,
},
  { name: "Balveer" ,
    image:"/members/balveer.jpeg",
},
  { name: "Golam Mansur Habib",
    image:"/members/golam.jpeg", 
},
  { name: "Suryan" ,
    image:"/members/suryan.jpeg",
},
]
