export const facultyCoordinator = {
  name: "Dr. Manjula D Ghatak",
  role: "Faculty Coordinator",
  designation:"HoD,Mechanical Engineering",
  image: "/team/faculty.jpg",
}

export const president = {
  name: "Mr. Pintu Kumar Shah",
  role: "President",
  image: "/team/president.jpg",
}

export const coreTeam = [
  {
    name: "Tapan Boruah",
    role: "Vice President",
    image: "/team/tapan.jpg",
  },
  {
    name: "Anshu Priya",
    role: "Finance Secretary",
    image: "/team/anshu.jpg",
  },
  {
    name: "Akash Raj",
    role: "Technical Lead",
    image: "/team/akash.jpg",
  },
  {
    name: "Atul Kumar",
    role: "Event Coordinator",
    image: "/team/atul.jpg",
  },
  {
    name: "Ayush Kumar",
    role: "Programming Coordinator",
    image: "/team/ayush.jpg",
  },
  {
    name: "Kombongappun Ering",
    role: "Editor-in-Chief",
    image: "/team/kombong.jpg",
  },
  {
    name: "Nitesh Kumar",
    role: "Hardware Lead",
    image: "/team/nitesh.jpg",
  },
  {
    name: "Krish Prasad",
    role: "Web Coordinator",
    image: "/team/krish.jpg",
  },

  {
    name: "Siddhant Hendry",
    role: "Overall Student Representative",
    image: "/team/siddhant.jpg",
  },
  {
    name: "Rachana Lamba",
    role: "First Year Representative",
    image: "/team/rachana.jpg",
  },
  {
    name: "Vishal Raghuwanshi",
    role: "First Year Representative",
    image: "/team/vishal.jpg",
  },
  {
    name: "Vaibhav Gupta",
    role: "Second Year Representative",
    image: "/team/vaibhav.jpg",
  },
]

export const members = [
  { name: "Ankit Shukla" ,
    image:"",
  },
  {name: "Roshni Yadav",
    image:"",
},
  { name: "Anupam Gupta",
    image:"" ,
},
  { name: "Subhajit Das",
    image:"" ,
},
  { name: "Dinkar Kumar Yadav",
    image:"" ,
},
  { name: "Jaisuria Barman",
    image:"" ,
},
  { name: "Abhyuday Sharma" ,
    image:"",
},
  { name: "Aditya Singh" ,
    image:"",
},
  { name: "Ravi Kumar Srivastav",
    image:"" ,
},
  { name: "Vishal" ,
    image:"",
},
  { name: "Aryan Kumar" ,
    image:"",
},
  { name: "Garvit Dumir" ,
    image:"",
},
  { name: "Kunal Thakur" ,
    image:"",
},
  { name: "Akhand Upadhyay",
    image:"" ,
},
  { name: "Ayush Yadav" ,
    image:"",
},
  { name: "Ankit Choudhary",
    image:"" ,
},
  { name: "Balveer" ,
    image:"",
},
  { name: "Golam Mansur Habib",
    image:"", 
},
  { name: "Suryan" ,
    image:"",
},
]
